export const letters: any = {
    English: {
        Total_Price: "Total Price",
        Finalize_Design_Payment: "Finalize Design & Payment",
        EACH_PRICE_MATTERS: "EACH PRICE MATTERS",
        EACH_SIZE_MATTERS: "EACH SIZE MATTERS",
        EACH_COLOR_MATTERS: "EACH COLOR MATTERS",
        EACH_MODEL_MATTERS: "EACH MODEL MATTERS",
        Frame_Price: "Frame Price",
        Drawer_Price: "Drawer Price",
        Interior_Price: "Shelf Price",
        Door_Price: "Door Price",
        Width: "Width",
        Height: "Height",
        Depth: "Depth",
        Length: "Length",
        Frame: "Frame",
        Interior: "Interior",
        Door: "Door",
        Concret: "Concret",
        Plain: "Plain",
        Glass: "Glass",
        Wooden: "Wooden",
        Metal: "Metal",
        Lenin: "Lenin",
        Apply_to_all: "Apply to all",
        Description: "Description",
        Shelve: "Shelve",
        Hanger: "Hanger",
        Drawer: "Drawer",
        Shelf: "Shelf",
        ROOM_MEASUREMENT: "ROOM MEASUREMENT",
        KD: "KD",
        Next: "Next",
        Back: "Back",
        Skip: "Skip",
        Last: "Last",
        Notification: "You should set material before click pay button!",
        Leave_Object: "Leave Product"
    },
    Arabic: {
        Total_Price: "السعر الاجمالي",
        Finalize_Design_Payment: "الانتهاء من التصميم والدفع",
        EACH_PRICE_MATTERS: "كل سعر مهم",
        EACH_COLOR_MATTERS: "كل لون مهم",
        EACH_SIZE_MATTERS: "كل حجم مهم",
        EACH_MODEL_MATTERS: "كل نموذج مهم",
        Frame_Price: "سعر الإطار",
        Drawer_Price: "سعر الدرج",
        Interior_Price: "سعر الرف",
        Door_Price: "سعر الباب",
        Width: "عرض",
        Height: "ارتفاع",
        Depth: "عمق",
        Length: "عمق",
        Frame: "إطار",
        Interior: "أرفف",
        Door: "باب",
        Concret: "الخرسانة",
        Plain: "سهل",
        Glass: "زجاج",
        Wooden: "خشبي",
        Metal: "معدن",
        Lenin: "لينين",
        Apply_to_all: "تنطبق على الجميع",
        Description: "وصف",
        Shelve: "الرف",
        Hanger: "شماعة",
        Shelf: "رف",
        Drawer: "درج",
        ROOM_MEASUREMENT: "قياسات الغرفة",
        KD: "د.ك",
        Next: "التالي",
        Back: "الرجوع",
        Skip: "تخطي",
        Last: "الأخيرة",
        Notification: "يجب عليك تعيين المواد قبل النقر على زر الدفع!",
        Leave_Object: "اترك العقار"
    }
}